config/routes.rb
Rails.application.routes.draw do

  get    "/search",                 to: "results#go_home"
  post   "/search",                 to: "results#search"#,           as: :search

  get    "/vendors",                to: "vendors#index",         as: :vendors
  get    "/vendors/:id",            to: "vendors#show",          as: :show_vendor
  get    "/vendors/:id/edit",       to: "vendors#edit_redirect"
  get    "/signup",                 to: "vendors#new",           as: :new_vendor
  post   "/signup",                 to: "vendors#create"
  get    "/dashboard",              to: "vendors#dashboard",     as: :dashboard
  get    "/edit",                   to: "vendors#edit",          as: :edit_vendor
  put    "/edit",                   to: "vendors#update"
  get    "/delete",                 to: "vendors#destroy_prep",  as: :delete_vendor
  delete "/delete",                 to: "vendors#destroy"

  get    "/login",                  to: "sessions#index",        as: :login
  post   "/login",                  to: "sessions#create"
  get    "/log-out",                to: "sessions#destroy"

  get    "/products",               to: "products#index",        as: :products
  get    "/products/new",           to: "products#new",          as: :new_product
  post   "/products/new",           to: "products#create"
  get    "/products/:id",           to: "products#show",         as: :show_product
  get    "/products/:id/edit",      to: "products#edit",         as: :edit_product
  put    "/products/:id",           to: "products#update"
  get    "/products/:id/delete",    to: "products#destroy_prep", as: :delete_product
  delete "/products/:id",           to: "products#destroy"

  get    "/sales",                  to: "sales#index",          as: :sales
  get    "/sales/new",              to: "sales#new",            as: :new_sale
  post   "/sales/new",              to: "sales#create"
  get    "/sales/:id",              to: "sales#show",           as: :show_sale

  get    "/markets",                to: "markets#index",         as: :markets
  get    "/markets/new",            to: "markets#new",           as: :new_market
  post   "/markets/new",            to: "markets#create"
  get    "/markets/:id",            to: "markets#show",          as: :show_market
  get    "/edit-markets",           to: "markets#edit_prep",     as: :edit_markets_landing
  post   "/edit-markets",           to: "markets#edit_post"
  get    "/markets/:id/edit",       to: "markets#edit",          as: :edit_market
  put    "/markets/:id",            to: "markets#update"

  root   "home#index"

end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  belongs_to :market
  has_many :products, dependent: :destroy
  has_many :sales, through: :products#, dependent: :destroy ## Needed to comment this out for now. Breaking vendor#destroy!

  validates :username, presence: true
  validates :email, presence: true
  validates :description, presence: true

  def self.authenticate(username)
    user = Vendor.find_by(username: username)
    user ? user : nil
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :vendor_not_found
  rescue_from NoMethodError, with: :vendor_not_found

  def index
    @vendors = Vendor.all
  end

  def new
    @vendor = Vendor.new
  end

  def create
    @vendor = Vendor.new(vendor_params)
    if @vendor.save
      session[:user_id] = @vendor.id
      redirect_to dashboard_path, :notice => "Vendor Created!"
    else
      render "new"
    end
  end

  def dashboard
    if session[:user_id]
      @vendor = current_user
      @vendor.market ? @current_market = @vendor.market.name : @current_market = "No Market Selected"
      @total_sales = total_sales_finder(@vendor)
    else
      redirect_to root_path
    end
  end

  def total_sales_finder(vendor)
    total = 0
    vendor.sales.each do |sale|
      total += sale.product.price.to_i
    end
    return total
  end

  def edit
    @vendor = current_user
    @markets = Market.all
    @vendor.market ? @current_market = @vendor.market.name : @current_market = "No Market Selected"
    @edit_markets = true if @markets.size > 0
  end

  def update
    @vendor = current_user
    # These are separated out, instead of using .update because there needs to be a catch for the market_id
    @vendor.username = params[:vendor][:username]
    @vendor.email = params[:vendor][:email]
    @vendor.description = params[:vendor][:description]
    @vendor.market_id = params[:vendor][:market_id] if params[:vendor][:market_id] != "select"

    if @vendor.save
      redirect_to dashboard_path, :notice => "Updated!"
    else
      flash.now.alert = "Something's wrong. Try again?"
      render "edit"
    end
  end

  def show
    find_vendor_no_session
  end

  def edit_redirect
    redirect_to vendors_path
  end

  def destroy_prep
    @vendor = current_user
  end

  def destroy
    current_user.destroy
    reset_session
    redirect_to root_path, :notice => "Vendor Deleted!"
  end


  private ## methods below here are protected from accidentally being used elsewhere

  def find_vendor_no_session
    @vendor = Vendor.find(params[:id]) if Vendor.find_by(id: params[:id])
  end

  def vendor_not_found
    redirect_to vendors_path
  end

  def vendor_params
    (params.require(:vendor).permit(:username, :email, :description))
  end
end

app/views/vendors/dashboard.html.erb
<h2>Vendor Dashboard</h2>

<div class="left-col">
  <strong>Welcome, <%= @vendor.username %></strong>
  <ul>
    <li>Email: <%= @vendor.email %></li>
    <li>Market: <%= @current_market %></li>
    <li>Description: <%= @vendor.description %></li>
  </ul>

  <div class="buttons">
    <a href="<%= edit_vendor_path %>"><button type="button">Edit Info</button></a>&nbsp;&nbsp;
    <a href="<%= sales_path %>"><button type="button">View My Sales</button></a>&nbsp;&nbsp;<a href="<%= new_sale_path %>"><button type="button">Create Sale</button></a>
  </div>

  <div class="total-sales">
    <strong>Total Sales: $<%= @total_sales %>.00</strong>
  </div>
</div>

<div class="right-col">
  <strong>My Products</strong>
  <ul>
    <% @vendor.products.each do |product| %>
      <li>
        <div class="product-link-dashboard"><%= link_to product.name, show_product_path(product.id) %></div>
        <%= link_to image_tag("edit.png", alt: "Edit Button"), edit_product_path(product.id) %>
        <%= link_to image_tag("delete.png", alt: "Delete Button"), delete_product_path(product.id) %>
      </li>
    <% end %>
  </ul>
  <a href="<%= new_product_path %>"><%= image_tag "add.png", alt: "Add Button" %> Product</a>
</div>

app/views/vendors/destroy_prep.html.erb
<h2>Delete Account</h2>

<form action="<%= delete_vendor_path %>" method="POST">
  <input type="hidden" name="_method" value="DELETE">
  <label for="submit">Are you sure you want to delete your account (<%= @vendor.username %>)? This will also delete all your products.</label>
  <br>
  <a href="<%= dashboard_path %>"><button type="button">Back</button></a>
  <input type="submit" value="Delete">
</form>

app/views/vendors/edit.html.erb
<h2>Edit My Information</h2>

<form action="/edit" method="POST">
  <input type="hidden" name="_method" value="PUT">
  <table>
    <tr>
      <td><label for="vendor[username]">Username:</label></td>
      <td><input type="text" name="vendor[username]" value="<%= @vendor.username %>"></td>
    </tr>
    <tr>
      <td><label for="vendor[email]">Email:</label></td>
      <td><input type="text" name="vendor[email]" value="<%= @vendor.email %>"></td>
    </tr>
    <tr>
      <td><label for="vendor[description]">Description:</label></td>
      <td><textarea name="vendor[description]"><%= @vendor.description %></textarea></td>
    </tr>
    <tr>
      <td><label for="vendor[market_id]">Current Market:</label></td>
      <td><%= @current_market %></td>
    </tr>
    <tr>
      <td>New Market:</td>
      <td>
        <select name="vendor[market_id]">
          <option value="select">Select Different Market...</option>
          <% @markets.each do |market|  %>
            <option value="<%= market.id %>"><%= market.name %></option>
          <% end %>
        </select>
      </td>
    </tr>
    <tr>
      <td></td>
      <td><%= link_to "Edit Markets", edit_markets_landing_path if @edit_markets %></td>
    </tr>
    <tr>
      <td></td>
      <td><a href="<%= new_market_path %>"><%= image_tag "add.png", alt: "Add Button" %> Market</a></td>
    </tr>
  </table>
  <a href="<%= dashboard_path %>"><button type="button">Back</button></a>
  <input type="submit" value="Update">
</form>

<br>
<a href="<%= delete_vendor_path %>"><button type="button" class="delete-button">Delete Account</button></a>

app/views/vendors/index.html.erb
<h2>View All Vendors</h2>

<% @vendors.each do |vendor| %>
  <strong><%= link_to vendor.username, show_vendor_path(vendor.id) %></strong>
  <ul>
    <li>Vendor Email: <%= vendor.email %></li>
    <li>Vendor Market: <%= vendor.market ? vendor.market.name : "No Market Selected" %></li>
    <li>Vendor Description: <%= vendor.description %></li>
    <li>Number of Products: <%= vendor.products.count %></li>
  </ul>
  <hr>
<% end %>

app/views/vendors/new.html.erb
<h2>Vendor Sign Up</h2>

<form action="<%= new_vendor_path %>" method="POST">
  <table>
    <tr>
      <td><label for="vendor[username]">Username:</label></td>
      <td><input type="text" name="vendor[username]" value="<%= @vendor.username %>"></td>
    </tr>
    <tr>
      <td><label for="vendor[email]">Email:</label></td>
      <td><input type="text" name="vendor[email]" value="<%= @vendor.email %>"></td>
    </tr>
    <tr>
      <td><label for="vendor[description]">Description:</label></td>
      <td><textarea name="vendor[description]" value="<%= @vendor.description %>"></textarea></td>
    </tr>
  </table>
  <input type="submit" value="Sign Up">
</form>

app/views/vendors/show.html.erb
<h2>Viewing Vendor: <%= @vendor.username %></h2>

<ul>
  <li>Email: <%= @vendor.email %></li>
  <li>Description: <%= @vendor.description %></li>
  <li>Market: <%= link_to @vendor.market.name, show_market_path(@vendor.market.id) if @vendor.market != nil %></li>
  <li><%= @vendor.products.count %> Products:</li>
  <% @vendor.products.each do |product| %>
    <ul>
      <li><%= link_to product.name, show_product_path(product.id) %></li>
    </ul>
  <% end %>
</ul>