config/routes.rb
Rails.application.routes.draw do

  get    "/search",                 to: "results#go_home"
  post   "/search",                 to: "results#search"#,           as: :search

  get    "/vendors",                to: "vendors#index",         as: :vendors
  get    "/vendors/:id",            to: "vendors#show",          as: :show_vendor
  get    "/vendors/:id/edit",       to: "vendors#edit_redirect"
  get    "/signup",                 to: "vendors#new",           as: :new_vendor
  post   "/signup",                 to: "vendors#create"
  get    "/dashboard",              to: "vendors#dashboard",     as: :dashboard
  get    "/edit",                   to: "vendors#edit",          as: :edit_vendor
  put    "/edit",                   to: "vendors#update"
  get    "/delete",                 to: "vendors#destroy_prep",  as: :delete_vendor
  delete "/delete",                 to: "vendors#destroy"

  get    "/login",                  to: "sessions#index",        as: :login
  post   "/login",                  to: "sessions#create"
  get    "/log-out",                to: "sessions#destroy"

  get    "/products",               to: "products#index",        as: :products
  get    "/products/new",           to: "products#new",          as: :new_product
  post   "/products/new",           to: "products#create"
  get    "/products/:id",           to: "products#show",         as: :show_product
  get    "/products/:id/edit",      to: "products#edit",         as: :edit_product
  put    "/products/:id",           to: "products#update"
  get    "/products/:id/delete",    to: "products#destroy_prep", as: :delete_product
  delete "/products/:id",           to: "products#destroy"

  get    "/sales",                  to: "sales#index",          as: :sales
  get    "/sales/new",              to: "sales#new",            as: :new_sale
  post   "/sales/new",              to: "sales#create"
  get    "/sales/:id",              to: "sales#show",           as: :show_sale

  get    "/markets",                to: "markets#index",         as: :markets
  get    "/markets/new",            to: "markets#new",           as: :new_market
  post   "/markets/new",            to: "markets#create"
  get    "/markets/:id",            to: "markets#show",          as: :show_market
  get    "/edit-markets",           to: "markets#edit_prep",     as: :edit_markets_landing
  post   "/edit-markets",           to: "markets#edit_post"
  get    "/markets/:id/edit",       to: "markets#edit",          as: :edit_market
  put    "/markets/:id",            to: "markets#update"

  root   "home#index"

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>US Farmers Markets</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='https://api.tiles.mapbox.com/mapbox.js/v2.1.2/mapbox.css' rel='stylesheet' >
  <script src='https://api.tiles.mapbox.com/mapbox.js/v2.1.2/mapbox.js'></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <nav id="login">
    <p class="notice" ><%= notice %></p>
    <p class="alert" ><%= alert %></p>
    <div id="login-wrapper">
      <% if current_user %>
        <%= link_to "My Dashboard", "/dashboard" %>
        <%= link_to "Log Out", "/log-out" %>
      <% else %>
        <%= link_to "Vendor Sign Up", new_vendor_path %>
        <%= link_to "Vendor Login", login_path %>
      <% end %>
    </div>
  </nav>

  <div id="main-nav">

    <!-- cow image was taken from http://en.wikipedia.org/wiki/File:Cow_closeup_03.svg -->
    <a href="/"><%= image_tag "farmar-cow.png", id: "cow", alt: "US Farmers Markets Cow Logo" %></a>

    <nav id="main-links">
      <%= link_to "VENDORS", vendors_path %>&nbsp;/&nbsp;<%= link_to "FARMERS MARKETS", markets_path %>&nbsp;/&nbsp;<%= link_to "PRODUCTS", products_path %>
    </nav>

    <form id="search" action="/search" method="POST">
      <input type="text" name="search" placeholder="Search">
      <input type="submit" value="Go!">
    </form>

  </div>


  <div id="wrapper">

    <div id="content">

      <%= yield %>

    </div>

  </div>



</body>
</html>